export const api = {
    settings : "/settings",
    login : "/auth",
    profile : "/profile",
    search_train : "/available-train",
    seat_layout : "/show-seat",
    seat_layout_with_auto_booking : "/show-seat-with-auto-reserve",
    select_seat : "/reserve-seat",
    unselect_seat : "/release-seat",
    unselect_seat : "/release-seat",
    bulk_unselect_seat : "/bulk-release-seat",
    passenger_details : "/passenger-details",
    resend_otp : "/resend-otp",
    verify_otp : "/verify-otp",
    confirm_ticket : "/confirm-ticket",
};